baseURL = 'https://nbrk.dev/'
languageCode = 'en-us'
title = "Nikola's personal blog"

[module]
[[module.imports]]
path = 'github.com/mirus-ua/hugo-theme-re-terminal'

[params]
themeColor = "red"

[languages.en.params.logo]
logoText = "Nikola's blog"

[markup.goldmark.renderer]
unsafe = true