name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'

      - name: Build site
        run: hugo --minify --gc

      - name: Publish to Cloudflare workers
        uses: cloudflare/wrangler-action@1.3.0
        with:
            apiToken: ${{ secrets.CF_API_TOKEN }}
