name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.131.0'
          extended: true
          
      - name: Build site
        run: hugo --minify --gc

      - name: Publish to Cloudflare workers
        uses: cloudflare/wrangler-action@v3
        with:
            apiToken: ${{ secrets.CF_API_TOKEN }}
